version: '3.9'
services:
  dev:
    build: .
    env_file:
      - ~/.rerdocker
    volumes:
      - .:/app
      - /app/node_modules
      - /app/vendor
    ports:
      - '3001:3001'
      - '4000:4000'
    command: npm run start
